version = 0.1
[default.deploy.parameters]
stack_name = "thailand-event-bridge"
resolve_s3 = true
s3_prefix = "thailand-event-bridge"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
