version = 0.1
[default.deploy.parameters]
stack_name = "order-manager-event-bridge"
resolve_s3 = true
s3_prefix = "order-manager-event-bridge"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
